[package]
name = "rdb-reader"
version = "0.1.0"
authors = ["Yuta Hongo <yutago@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
error-chain = "0.12.1"
byteorder = "1.4.2"